export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST";
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS";
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL";


export const SINGLE_PROJECT_REQUEST =  "SINGLE_PROJECT_REQUEST";
export const SINGLE_PROJECT_SUCCESS =  "SINGLE_PROJECT_SUCCESS";
export const SINGLE_PROJECT_FAIL =  "SINGLE_PROJECT_FAIL";




export const CLEAR_ERRORS = "CLEAR_ERRORS";
